<a href="https://colab.research.google.com/github/tomaravi7/big-data-assignments/blob/main/assignment2_31jan_202301013.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# big_data_assignments
import numpy as np

In [ ]:
arr=np.array([1,2,3,6,4,5])
np.flip(arr)

array([5, 4, 6, 3, 2, 1])

In [4]:
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1,arr2))

True


In [33]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, count=np.unique(x,return_counts=True)
print("Most frequent Number is : ",x[np.argmax(count)],end=" ")
indxes = np.where(x==x[np.argmax(count)])
print("And is present at ",indxes," indexes")

Most frequent Number is :  1 And is present at  (array([0, 5, 7, 8, 9]),)  indexes


In [44]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum=gfg.sum()
sum_row=np.sum(gfg,axis=1)
sum_column=np.sum(gfg,axis=0)
print(sum,sum_row,sum_column)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
45 [[14]
 [16]
 [15]] [[20  9 16]]
